### ISSUE TITLE
DNA Sequences Embedding

### ISSUE THREAD

**Issue by elbasir** [jerryji1993/DNABERT#11]
Hi, 
Thanks for this very good work. I was wondering if I can retrieve the embedding from DNA sequences that I would train and use them later then for down stream tasks. Can you please confirm that with me and guide me on how I can get the embedding?

Thanks!

**Comment by Zhihan1996** [comment]
Hi,

Yes, you can do this.  Please refer to the `line 420` of https://github.com/jerryji1993/DNABERT/blob/master/examples/run_finetune.py. The variable `logits` stands for the embedding of the DNA sequence. You can directly use it.

**Comment by elbasir** [comment]
Hi, 
Thanks for your answer. I have checked the embedding using the variable logits and I found out the embedding size is only 2-dimensional vector for each DNA sequence. I have a sequence that's longer than 500 bps, would it be possible to extend the embedding size or you think the current embedding size is enough to represent a long DNA sequence?

**Comment by Zhihan1996** [comment]
Hi,

I am sorry that I was wrong in the last response. The 2-dimensional logits here is essentially the classification results of the given sequence, where each dimension stands for the probability of this sequence belongs to each class. The embedding for each sequence should be a 768-dimensional vector. You can achieve it by 

```
import torch
from transformers import BertModel, BertConfig, DNATokenizer

dir_to_pretrained_model = "xxx/xxx"

config = BertConfig.from_pretrained('https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/config.json')
tokenizer = DNATokenizer.from_pretrained('dna6')
model = BertModel.from_pretrained(dir_to_pretrained_model, config=config)

sequence = "AATCTA ATCTAG TCTAGC CTAGCA"
model_input = tokenizer.encode_plus(sequence, add_special_tokens=True, max_length=512)["input_ids"]
model_input = torch.tensor(model_input, dtype=torch.long)
model_input = model_input.unsqueeze(0)   # to generate a fake batch with batch size one

output = model(model_input)
```
Here the `output[1]` is the embedding of the input sequence. 

For the current version, if you have sequences longer than 512, then you need either cut it to 512 or split it into multiple pieces of 512 lengths and concatenate their embedding together.

**Comment by elbasir** [comment]
Thanks a lot!

**Comment by iamysk** [comment]
Hi,

How do I get embeddings of multiple sequences at once? I tried with a list of sequences, but the output is always a 1x768 vector. 

Thanks.

**Comment by maiskovich** [comment]
> Hi,
> 
> I am sorry that I was wrong in the last response. The 2-dimensional logits here is essentially the classification results of the given sequence, where each dimension stands for the probability of this sequence belongs to each class. The embedding for each sequence should be a 768-dimensional vector. You can achieve it by
> 
> ```
> import torch
> from transformers import BertModel, BertConfig, DNATokenizer
> 
> dir_to_pretrained_model = "xxx/xxx"
> 
> config = BertConfig.from_pretrained('https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/config.json')
> tokenizer = DNATokenizer.from_pretrained('dna6')
> model = BertModel.from_pretrained(dir_to_pretrained_model, config=config)
> 
> sequence = "AATCTA ATCTAG TCTAGC CTAGCA"
> model_input = tokenizer.encode_plus(sequence, add_special_tokens=True, max_length=512)["input_ids"]
> model_input = torch.tensor(model_input, dtype=torch.long)
> model_input = model_input.unsqueeze(0)   # to generate a fake batch with batch size one
> 
> output = model(model_input)
> ```
> 
> Here the `output[1]` is the embedding of the input sequence.
> 
> For the current version, if you have sequences longer than 512, then you need either cut it to 512 or split it into multiple pieces of 512 lengths and concatenate their embedding together.

I tried this code and when running it inside a for loop I was always getting the process killed as it was using too much memory, I needed to put the prediction part inside `with torch.no_grad():`, It ended looking like this:

```import torch
from transformers import BertModel, BertConfig, DNATokenizer

dir_to_pretrained_model = "xxx/xxx"

config = BertConfig.from_pretrained('https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/config.json')
tokenizer = DNATokenizer.from_pretrained('dna6')
model = BertModel.from_pretrained(dir_to_pretrained_model, config=config)

sequence = "AATCTA ATCTAG TCTAGC CTAGCA"
with torch.no_grad():
        model_input = tokenizer.encode_plus(sequence, add_special_tokens=True, max_length=512)["input_ids"]
        model_input = torch.tensor(model_input, dtype=torch.long)
        model_input = model_input.unsqueeze(0)   # to generate a fake batch with batch size one
        
        output = model(model_input)```

**Comment by asimokby** [comment]
> Hi,
> 
> I am sorry that I was wrong in the last response. The 2-dimensional logits here is essentially the classification results of the given sequence, where each dimension stands for the probability of this sequence belongs to each class. The embedding for each sequence should be a 768-dimensional vector. You can achieve it by
> 
> ```
> import torch
> from transformers import BertModel, BertConfig, DNATokenizer
> 
> dir_to_pretrained_model = "xxx/xxx"
> 
> config = BertConfig.from_pretrained('https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/config.json')
> tokenizer = DNATokenizer.from_pretrained('dna6')
> model = BertModel.from_pretrained(dir_to_pretrained_model, config=config)
> 
> sequence = "AATCTA ATCTAG TCTAGC CTAGCA"
> model_input = tokenizer.encode_plus(sequence, add_special_tokens=True, max_length=512)["input_ids"]
> model_input = torch.tensor(model_input, dtype=torch.long)
> model_input = model_input.unsqueeze(0)   # to generate a fake batch with batch size one
> 
> output = model(model_input)
> ```
> 
> Here the `output[1]` is the embedding of the input sequence.
> 
> For the current version, if you have sequences longer than 512, then you need either cut it to 512 or split it into multiple pieces of 512 lengths and concatenate their embedding together.

Thank you this is very helpful! 

If you run this snippet in a script that lives in the parent directory, the same level as the examples folder, you may run into some problems. 

I had to change the following two imports in **modeling_albert.py**: 
`
from transformers.configuration_albert import AlbertConfig
from transformers.modeling_bert import ACT2FN, BertEmbeddings, BertSelfAttention, prune_linear_layer
`

to the following: 

`
from transformers.models.albert.configuration_albert import AlbertConfig
from transformers.models.bert.modeling_bert import ACT2FN, BertEmbeddings, BertSelfAttention, prune_linear_layer
`

Also, I made a change to the snippet to get it to work. I changed the following import statement: 

`
from transformers import BertModel, BertConfig, DNATokenizer
`

to 

`
from src.transformers import DNATokenizer
from transformers import BertModel, BertConfig
`

**Comment by ChengkuiZhao** [comment]
Hello, I just want to import the DNATokenizer from the transformers, but there is wrong with 'ImportError: cannot import name 'DNATokenizer'', can you help me to solve this? Google doesn't tell me anything about it...

**Comment by ChengkuiZhao** [comment]
> 



> > Hello, I just want to import the DNATokenizer from the transformers, but there is wrong with 'ImportError: cannot import name 'DNATokenizer'', can you help me to solve this? Google doesn't tell me anything about it...
> 
> You should clone it in right directory, because DNATokenizer is inside of the DNABERT folder.
> 
> Try this,
> 
> !git clone https://github.com/jerryji1993/DNABERT %cd DNABERT !python3 -m pip install --editable . %cd examples !python3 -m pip install -r requirements.txt
> 
> and run import in this directory. cd "DNABERT/examples" then it should import the DNATokenizer.

Actually I didn't use the DNATokenizer, and used the BERTTokenizer instead. The code also works, is this two way different and make much difference? 
Thank you so much for your reply.

**Comment by aliakay** [comment]
> > 
> 
> > > Hello, I just want to import the DNATokenizer from the transformers, but there is wrong with 'ImportError: cannot import name 'DNATokenizer'', can you help me to solve this? Google doesn't tell me anything about it...
> > 
> > 
> > You should clone it in right directory, because DNATokenizer is inside of the DNABERT folder.
> > Try this,
> > !git clone https://github.com/jerryji1993/DNABERT %cd DNABERT !python3 -m pip install --editable . %cd examples !python3 -m pip install -r requirements.txt
> > and run import in this directory. cd "DNABERT/examples" then it should import the DNATokenizer.
> 
> Actually I didn't use the DNATokenizer, and used the BERTTokenizer instead. The code also works, is this two way different and make much difference? Thank you so much for your reply.

As far as understand,DNATokenizer is specifically trained by DNA Sequences on the other side, BERT Tokenizer is tokenizer for sentences, so you will get different input values when you run both tokenizer which effect your output.

**Comment by ChengkuiZhao** [comment]
> > Hi,
> > I am sorry that I was wrong in the last response. The 2-dimensional logits here is essentially the classification results of the given sequence, where each dimension stands for the probability of this sequence belongs to each class. The embedding for each sequence should be a 768-dimensional vector. You can achieve it by
> > ```
> > import torch
> > from transformers import BertModel, BertConfig, DNATokenizer
> > 
> > dir_to_pretrained_model = "xxx/xxx"
> > 
> > config = BertConfig.from_pretrained('https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/config.json')
> > tokenizer = DNATokenizer.from_pretrained('dna6')
> > model = BertModel.from_pretrained(dir_to_pretrained_model, config=config)
> > 
> > sequence = "AATCTA ATCTAG TCTAGC CTAGCA"
> > model_input = tokenizer.encode_plus(sequence, add_special_tokens=True, max_length=512)["input_ids"]
> > model_input = torch.tensor(model_input, dtype=torch.long)
> > model_input = model_input.unsqueeze(0)   # to generate a fake batch with batch size one
> > 
> > output = model(model_input)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here the `output[1]` is the embedding of the input sequence.
> > For the current version, if you have sequences longer than 512, then you need either cut it to 512 or split it into multiple pieces of 512 lengths and concatenate their embedding together.
> 
> Dear Zihian,
> 
> I would like to use DNABert to get short dna sequence representation in order to keep sequencing relationship instead of using one hot encoder method and I want to put this values to another model for my desire, is it good use directly embedding representation which is output[1] or attention score would be work also for representation?

I did some research on the output of this model, the output[0] is the last_hidden_state (https://huggingface.co/docs/transformers/main_classes/output), I saw people used output[0][ : , 0 , : ] which means the 768 dimension vector for the 'CLS' in the last hidden layer  for the following model, and that works for me. I think the attention score is not for the output representation.

**Comment by WENHUAN22** [comment]
Dear authors,

I have a question about obtaining embedding vectors of my data.
For example, the first record in my dataset is  "AATCTA ATCTAG TCTAGC CTAGCA".

May I use
model.embeddings.word_embeddings.weight[0]
as the embedding vector of my first sample?
Is there any difference between the method you introduce above (output[1]) and this one?

And after I have embedding vectors I am going to build a classifier on them. It will be nice if you tell me whether this thought is correct or not.

**Comment by palset** [comment]
> Hi,
> 
> I am sorry that I was wrong in the last response. The 2-dimensional logits here is essentially the classification results of the given sequence, where each dimension stands for the probability of this sequence belongs to each class. The embedding for each sequence should be a 768-dimensional vector. You can achieve it by
> 
> ```
> import torch
> from transformers import BertModel, BertConfig, DNATokenizer
> 
> dir_to_pretrained_model = "xxx/xxx"
> 
> config = BertConfig.from_pretrained('https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/config.json')
> tokenizer = DNATokenizer.from_pretrained('dna6')
> model = BertModel.from_pretrained(dir_to_pretrained_model, config=config)
> 
> sequence = "AATCTA ATCTAG TCTAGC CTAGCA"
> model_input = tokenizer.encode_plus(sequence, add_special_tokens=True, max_length=512)["input_ids"]
> model_input = torch.tensor(model_input, dtype=torch.long)
> model_input = model_input.unsqueeze(0)   # to generate a fake batch with batch size one
> 
> output = model(model_input)
> ```
> 
> Here the `output[1]` is the embedding of the input sequence.
> 
> For the current version, if you have sequences longer than 512, then you need either cut it to 512 or split it into multiple pieces of 512 lengths and concatenate their embedding together.


I see that the model_input, which is returned by the tokenizer.encode_plus, does not have padding on the left or right, even though the input size is < 512. If I add padding on the right, the embedding generated by DNABERT changes. So, what according to you is the correct format? Should I manually add padding on the right, or just ignore it?
Thanks for the great work!

**Comment by pengxiand** [comment]
Dear all, I use the huggingface dnabert6 and try it with code:
`import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM

tokenizer = AutoTokenizer.from_pretrained("armheb/DNA_bert_6")

model = AutoModelForMaskedLM.from_pretrained("armheb/DNA_bert_6")


sequence = "AATCTA ATCTAG TCTAGC CTAGCA"
model_input = tokenizer.encode_plus(sequence, add_special_tokens=False, max_length=512)["input_ids"]
print(model_input)
model_input = torch.tensor(model_input, dtype=torch.long)
model_input = model_input.unsqueeze(0)   # to generate a fake batch with batch size one

output = model(model_input)
print(output)
print(type(output))
print(output[0])
output[0].size()`

The output are
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
[105, 408, 1619, 2365]
MaskedLMOutput(loss=None, logits=tensor([[[-3.9969, -3.2175, -2.7966,  ..., -7.9246, -6.1943, -8.7459],
         [-2.4686, -3.8707, -2.7061,  ..., -4.8401, -2.7722, -4.7418],
         [-2.7123, -3.5053, -2.9562,  ..., -5.9612, -3.0480, -5.8253],
         [-3.3073, -2.8556, -3.2893,  ..., -8.1870, -5.7713, -8.3609]]],
       grad_fn=<ViewBackward0>), hidden_states=None, attentions=None)
<class 'transformers.modeling_outputs.MaskedLMOutput'>
tensor([[[-3.9969, -3.2175, -2.7966,  ..., -7.9246, -6.1943, -8.7459],
         [-2.4686, -3.8707, -2.7061,  ..., -4.8401, -2.7722, -4.7418],
         [-2.7123, -3.5053, -2.9562,  ..., -5.9612, -3.0480, -5.8253],
         [-3.3073, -2.8556, -3.2893,  ..., -8.1870, -5.7713, -8.3609]]],
       grad_fn=<ViewBackward0>)
torch.Size([1, 4, 4101])

Could you please help me with that? Why 4101

**Comment by CharlsonLiu** [comment]
> > Hello, I just want to import the DNATokenizer from the transformers, but there is wrong with 'ImportError: cannot import name 'DNATokenizer'', can you help me to solve this? Google doesn't tell me anything about it...
> 
> You should clone it in right directory, because DNATokenizer is inside of the DNABERT folder.
> 
> Try this,
> 
> !git clone https://github.com/jerryji1993/DNABERT %cd DNABERT !python3 -m pip install --editable . %cd examples !python3 -m pip install -r requirements.txt
> 
> and run import in this directory. cd "DNABERT/examples" then it should import the DNATokenizer.

Hi,i just did what u said,but still got this:
'ImportError: cannot import name 'DNATokenizer''.i dont know which step(s) was/were wrong

**Comment by fahimfarhan** [comment]
> For the current version, if you have sequences longer than 512, then you need either cut it to 512 or split it into multiple pieces of 512 lengths and concatenate their embedding together.

My sequence length is longer than 512. I tried to split into sub-sequences, and concatenate the embeddings together. This is my code. Is this okay? If not, could you help me by providing a sample code?

```python
def preprocess_dna_sequence(
    tokenizer: BertTokenizer,
    sequence: str,
    label: int, # 1 or 0 for binary classification
    max_length: int=512
):

  # Load the DNABERT tokenizer

  # Split the sequence into subsequences of length max_length
  subsequences = [sequence[i:i + max_length] for i in range(0, len(sequence), max_length)]

  # Tokenize each subsequence
  tokenized = [tokenizer(subseq, padding='max_length', truncation=True, max_length=max_length, return_tensors="pt")
               for subseq in subsequences]

  # Concatenate tokenized subsequences along dim=0
  input_ids = torch.cat([t['input_ids'] for t in tokenized], dim=0)
  attention_mask = torch.cat([t['attention_mask'] for t in tokenized], dim=0)
  token_type_ids = torch.cat([t['token_type_ids'] for t in tokenized], dim=0) if 'token_type_ids' in tokenized[
    0] else None

  print(f"{input_ids = }, {input_ids.shape = }, { input_ids.size = }")
  print(f"{attention_mask = }, {attention_mask.shape = }, { attention_mask.size = }")
  print(f"{token_type_ids = }, {token_type_ids.shape = }, { token_type_ids.size = }")
  # Return concatenated tensors
  return {
    "input_ids": input_ids,
    "attention_mask": attention_mask,
    "token_type_ids": token_type_ids,
    "labels": label
  }

if __name__ == '__main__':
   model = BertModel.from_pretrained(pretrained_model_name_or_path=DNA_BERT_6)
   tokenizer = BertTokenizer.from_pretrained(pretrained_model_name_or_path=DNA_BERT_6)

  seq = "CACACCGATGAACGAGTGTCTGAG... ... ..."  # example sequence length = 2048

  preprocessed_input = preprocess_dna_sequence(tokenizer=tokenizer, sequence=seq, label=1, max_length=512)
  print(f"{preprocessed_input = }")
  print(f"{preprocessed_input['input_ids'].shape = }")
  print(f"{preprocessed_input['attention_mask'].shape = }")
  print(f"{preprocessed_input['token_type_ids'].shape = }")
  print(f"{preprocessed_input['labels'] = }")
  pass

```

And the output is:
```bash
preprocessed_input = {'input_ids': tensor([[2, 1, 3,  ..., 0, 0, 0],
        [2, 1, 3,  ..., 0, 0, 0],
        [2, 1, 3,  ..., 0, 0, 0],
        [2, 1, 3,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'label': 1}
preprocessed_input['input_ids'].shape = torch.Size([4, 512])
preprocessed_input['attention_mask'].shape = torch.Size([4, 512])
preprocessed_input['token_type_ids'].shape = torch.Size([4, 512])
preprocessed_input['labels'] = 1
```
