### ISSUE TITLE
run_finetine.py issue

### ISSUE THREAD

**Issue by alexandremarcil** [jerryji1993/DNABERT#12]
When running the test.sh script (run_fintune.py), I am getting the following error message:

<class 'transformers.tokenization_dna.DNATokenizer'>
01/18/2021 11:20:34 - INFO - transformers.tokenization_utils -   loading file https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/vocab.txt from cache at /home/mcb/users/zipcode/.cache/torch/transformers/ea1474aad40c1c8ed4e1cb7c11345ddda6df27a857fb29e1d4c901d9b900d32d.26f8bd5a32e49c2a8271a46950754a4a767726709b7741c68723bc1db840a87e
01/18/2021 11:20:34 - INFO - transformers.modeling_utils -   loading weights file /home/mcb/users/zipcode/code/DNABERT/6-new-12w-0/pytorch_model.bin
01/18/2021 11:20:40 - INFO - transformers.modeling_utils -   Weights of BertForSequenceClassification not initialized from pretrained model: ['classifier.weight', 'classifier.bias']
01/18/2021 11:20:40 - INFO - transformers.modeling_utils -   Weights from pretrained model not used in BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias']
01/18/2021 11:20:54 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, attention_probs_dropout_prob=0.1, beta1=0.9, beta2=0.999, cache_dir='', config_name='', data_dir='sample_data/ft/prom-core/6', device=device(type='cuda', index=8), do_ensemble_pred=False, do_eval=True, do_lower_case=False, do_predict=False, do_train=True, do_visualize=False, early_stop=0, eval_all_checkpoints=False, evaluate_during_training=True, fp16=False, fp16_opt_level='O1', gradient_accumulation_steps=1, hidden_dropout_prob=0.1, learning_rate=0.0002, local_rank=-1, logging_steps=100, max_grad_norm=1.0, max_seq_length=75, max_steps=-1, model_name_or_path='/home/mcb/users/zipcode/code/DNABERT/6-new-12w-0', model_type='dna', n_gpu=1, n_process=8, no_cuda=False, num_rnn_layer=2, num_train_epochs=3.0, output_dir='./ft/prom-core/6', output_mode='classification', overwrite_cache=False, overwrite_output_dir=True, per_gpu_eval_batch_size=16, per_gpu_pred_batch_size=8, per_gpu_train_batch_size=16, predict_dir=None, predict_scan_size=1, result_dir=None, rnn='lstm', rnn_dropout=0.0, rnn_hidden=768, save_steps=4000, save_total_limit=None, seed=42, server_ip='', server_port='', should_continue=False, task_name='dnaprom', tokenizer_name='dna6', visualize_data_dir=None, visualize_models=None, visualize_train=False, warmup_percent=0.1, warmup_steps=0, weight_decay=0.01)
01/18/2021 11:20:54 - INFO - __main__ -   Loading features from cached file sample_data/ft/prom-core/6/cached_train_6-new-12w-0_75_dnaprom
Traceback (most recent call last):
  File "run_finetune.py", line 1288, in <module>
    main()
  File "run_finetune.py", line 1102, in main
    train_dataset = load_and_cache_examples(args, args.task_name, tokenizer, evaluate=False)
  File "run_finetune.py", line 704, in load_and_cache_examples
    features = torch.load(cached_features_file)
  File "/home/mcb/users/zipcode/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/mcb/users/zipcode/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579027003190/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /opt/conda/conda-bld/pytorch_1579027003190/work/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f2c10e32627 in /home/mcb/users/zipcode/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f2a99e01e2b in /home/mcb/users/zipcode/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f2a99e03044 in /home/mcb/users/zipcode/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6d1326 (0x7f2c11aca326 in /home/mcb/users/zipcode/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x28c076 (0x7f2c11685076 in /home/mcb/users/zipcode/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #40: __libc_start_main + 0xe7 (0x7f2c154d4bf7 in /lib/x86_64-linux-gnu/libc.so.6)

Any idea how to fix this?  PyTorch version 1.4.0.

**Comment by Zhihan1996** [comment]
Hi, it seems this problem is related to your pytorch version. Could you please update your version(e.g., newer than 1.4.0), delete the cache file and retry it?

**Comment by jerryji1993** [comment]
Closed.
