### ISSUE TITLE
Fine-tuning for multiclass data

### ISSUE THREAD

**Issue by appledora** [jerryji1993/DNABERT#15]
Hi, I am working with a dataset that has around 60 classes labeled from 0 - 59. I created a new `DataProcessor` for the task first which returns those labels on `get_labels()` function. 

However, after following the  `pre-training` script in the READme.md i get a keyerror :
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mr/miniconda3/envs/bert/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/mr/Workspace/Team8993/THESIS/DNABERT/examples/transformers/data/processors/glue.py", line 120, in glue_convert_examples_to_features
    label = label_map[example.label]
KeyError: '35'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_finetune.py", line 1283, in <module>
    main()
  File "run_finetune.py", line 1097, in main
    train_dataset = load_and_cache_examples(args, args.task_name, tokenizer, evaluate=False)
  File "run_finetune.py", line 760, in load_and_cache_examples
    features.extend(result.get())
  File "/home/mr/miniconda3/envs/bert/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: '35'
```

Can you please tell me where this might be originating from?

**Comment by Zhihan1996** [comment]
Hi,

I think you need to modify the `src/transformers/data/processors/glue.py`. First, define your data processor as the `DnaPromProcessor`, and update the three dictionaries at `line 596-644` (you need to define a name for your own task). When running the code, specify the task name with `--task_name YOURTASK`.

**Comment by appledora** [comment]
Hey, thanks for your help. I have successfully ran fine-tuning, prediction and visualization script on a demo dataset. However, I have a little confusion about the dataset. During fine-tuning I don't see it using any validation set. Again, during visualization the script requires a `dev.tsv`.  could you kindly tell me 
* which scripts are actually utilizing the `test.tsv` and `dev.tsv` ? 
* Should I divide my dataset into non-overlapping 3 sections? 
* Which `.tsv` is being used for validation? 
Thanks and regards.

**Comment by Joseph-Vineland** [comment]
@appledora 

3. Fine-tune 
The `run_finetune.py` script will fine-tune the DNABERT model using `train.tsv` .  Once fine tuning is complete, the script will test the performance of the fine-tuned model using `dev.tsv` (provide the argument `--do_eval`).  Additionally, `run_finetune.py` can evaluate performance on `dev.tsv` periodically _during_ fine-tuning (provide the arguments `--evaluate_during_training` and 
`--logging_steps 1000`).  

4. Prediction
Once fine-tuning is complete, if you run the `run_finetune.py` script, it will generate predictions with `dev.tsv` and save them to `pred.npy`.  

I divide my data into a train, a dev, and a test set.  However, this means I have to rename my dev set file as `dev_true.tsv` and my test set file as `dev.tsv` between steps 3 and 4!  I can see how one might become confused.

I hope this helps.

**Comment by appledora** [comment]
yeah...i eventually had to do the renaming step as i went along running the repo. Thanks for your detailed explanations, either way!

**Comment by smruti241** [comment]
@appledora  or @Zhihan1996 can you please tell me how to finetune the unlabeled kmer data with pretrained models

**Comment by dominiclopez391** [comment]
> Hi,
> 
> I think you need to modify the `src/transformers/data/processors/glue.py`. First, define your data processor as the `DnaPromProcessor`, and update the three dictionaries at `line 596-644` (you need to define a name for your own task). When running the code, specify the task name with `--task_name YOURTASK`.

You'll also need to add your task name to your metrics  in /src/transformers/data/metrics/__init__.py or you're going to error during validation :)
