### ISSUE TITLE
On getting last hidden layer weights through python

### ISSUE THREAD

**Issue by maricatovictor** [jerryji1993/DNABERT#16]
Hi,

I want to run the DNABERT model to a given sequence loaded in python, e.g.:

```python
sequence = "ATCTACTACTGTACTACGTAG"
```

Currently, the documentation supports only running sequences through CLI. What is the best way to load the DNABERT model so I can do something like:

```python
kmer_sequence = some_kmer_function(sequence)
embedding = DNABERT(kmer_sequence).last_hidden_states
```

This `DNABERT(kmer_sequence).last_hidden_outputs` I took from [HF documentation](https://huggingface.co/transformers/model_doc/bert.html#tfbertmodel).

**Comment by Zhihan1996** [comment]
Hi,

Please refer to jerryji1993/DNABERT#11 for the embedding problem. That code uses the [CLS] token's hidden state as the sequence embedding. If you want to average the hidden states of all the tokens, please use `output[0]`.  It should be a tensor in the shape  of `(batch_size, sequence_length, hidden_size)`, each of which stands for the last hidden state of each token.
