### ISSUE TITLE
Pre-trained weights for long sequence models

### ISSUE THREAD

**Issue by ninashenker** [jerryji1993/DNABERT#22]
Hi,

I am looking for pre-trained weights for the BertForLongSequenceClassification/BertForLongSequenceClassificationCat models. Are these available? Any kmer split would be fine but ideally 4-mer. 

Thanks,
Nina

**Comment by Zhihan1996** [comment]
Hi, 

we use the same weight for both BertForLongSequenceClassification and BertForSequenceClassification. So please directly use the given checkpoints.

**Comment by ninashenker** [comment]
Do you mean the values under DNABERT/src/transformers/dnabert-config/bert-config-4, for example?

**Comment by Zhihan1996** [comment]
No. This is just a config file, which specifies the hyperparameters of the model. The real model parameters for DNABERT4 are stored in https://northwestern.box.com/s/rmmepi2upskgob4fgeohdwh1r5w37oqo. Please refer to the README file for links to other models.

**Comment by ninashenker** [comment]
I see, thank you! 

However, the keys don't seem to match the long sequence models.
Shouldn't it have a module named rnn somewhere?
