### ISSUE TITLE
No module named 'transformers' error

### ISSUE THREAD

**Issue by HeejoNam** [jerryji1993/DNABERT#3]
Hi, I am Heejo.
Thank you for the amazing package!
I followed your guide and got an error in run_finetune.py

Traceback (most recent call last):
  File "run_finetune.py", line 36, in <module>
    from transformers import (
ModuleNotFoundError: No module named 'transformers'

I think that I should not install the module using 'pip install transformers'
because you extended the code from huggingface.
How can I install your modified transformers package?

**Comment by vedashreebhandare** [comment]
Hello @HeejoNam How did you resolve this error? I am getting a similar error when I run finetune.py. Thanks for your help in advance
