### ISSUE TITLE
How the DNABERT pre-train with long sequences?

### ISSUE THREAD

**Issue by Celestial-Bai** [jerryji1993/DNABERT#30]
HI!

Today I found that there is not a selection called "dnalong" in the pre-training process. Actually it only exists in the fine-tuning part.
Here I wonder if there will be some problems if I use "dna" to pre-train by using long sequences. For example, if I use the 1000bp-long sequences, what problems will I meet?
Although I knew there were some issues about how the DNABERT deals with the long sequences, I browsed them and thought they could not solve this issue.
Thank you so much in advance!

**Comment by BinchaoPeng** [comment]
hi，do you solve it？can we have a talk in QQ，64604790

**Comment by Celestial-Bai** [comment]
> hi，do you solve it？can we have a talk in QQ，646047990

Of course not. I want to hear their suggestions in fact.

**Comment by BinchaoPeng** [comment]
> 嗨，你解决了吗？我们可以用QQ讲话，64604790



> > hi，do you solve it？can we have a talk in QQ，646047990
> 
> Of course not. I want to hear their suggestions in fact.

能加个qq吗？想请教一下具体怎么使用？我是按照huggingface来使用的，但是作者是按照命令行来写readme的，不知你是如何使用和学习这个模型的的，如果可以，希望可以交流一下

**Comment by Celestial-Bai** [comment]
> > 嗨，你解决了吗？我们可以用QQ讲话，64604790
> 
> > > hi，do you solve it？can we have a talk in QQ，646047990
> > 
> > 
> > Of course not. I want to hear their suggestions in fact.
> 
> 能加个qq吗？想请教一下具体怎么使用？我是按照huggingface来使用的，但是作者是按照命令行来写readme的，不知你是如何使用和学习这个模型的的，如果可以，希望可以交流一下

很抱歉回复这么晚了，DNABERT本质就是huggingface的extension，所以按照huggingface来使用是没有问题的

**Comment by Celestial-Bai** [comment]
> @Celestial-Bai BERT has a maximum window of 512 tokens if I'm not mistaken. This model / repo is mainly useful for the pre-trained models in my view. If you're going to pre-train again, you might instead want to look into longformer or other alternatives if you require 1000+bp, and take from here some of the preprocessing logic.

@simonlevine Sorry for my late reply. I finally to fix the segment length to 500 bp. Thanks!
