### ISSUE TITLE
DNABERT-XL availability

### ISSUE THREAD

**Issue by victormaricato** [jerryji1993/DNABERT#39]
Greetings everyone,

In the paper, you mentioned that to get promo-regions prediction, TF-binding motifs and variants prediction outside coding regions, the DNABERT-XL was used, which takes sequences sizes of 10k bp.

Is/will be this model available?

Ty!

**Comment by Zhihan1996** [comment]
Please use the tag  `--model_type=dnalong` and set the `--block_size` as a multiple of 512.

**Comment by victormaricato** [comment]
Is it possible to do that from python? @Zhihan1996

**Comment by Zhihan1996** [comment]
Yes. When running the code with `python run_finetune.py ....`, just add these tags.

**Comment by victormaricato** [comment]
Sorry, I meant in a use case similar to https://github.com/jerryji1993/DNABERT/issues/16

**Comment by Zhihan1996** [comment]
No problem. DNABERT-XL just split the DNA sequence into non-overlapped pieces, calculate embedding for each of them and concatenate the embeddings together as the final embedding. To get the embedding for DNA sequences longer than 512 as #16, you can manually split the sequence into pieces, calculate embedding for each of them and take the average/max of them as the embedding.
