### ISSUE TITLE
training issue

### ISSUE THREAD

**Issue by gianfilippo** [jerryji1993/DNABERT#9]
Hi,

I tried to train from scratch to reproduce the paper results. I started from the genome fasta, split it into 510 sub-sequences with the BBMap script shred.sh.

I found a function under the DNABERT data_process_template folder process_pretrain_data.py to generate split sequences into k-mers (though I am not sure about the "sampling_rate"). Anyway, I used the vocab.txt under bert-config-6.

I ran the run_pretrain.py as described, with the same parameters. I get the error below. Can you please help ?

01/08/2021 01:44:15 - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 1, distributed training: False, 16-bits training: True
01/08/2021 01:44:15 - INFO - transformers.configuration_utils -   loading configuration file /home/DNABERT/src/transformers/dnabert-config/bert-config-6-mm/config.json
01/08/2021 01:44:15 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "do_sample": false,
  "eos_token_ids": 0,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_beams": 1,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "num_return_sequences": 1,
  "num_rnn_layer": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": 0,
  "pruned_heads": {},
  "repetition_penalty": 1.0,
  "rnn": "lstm",
  "rnn_dropout": 0.0,
  "rnn_hidden": 768,
  "split": 10,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 4101
}

01/08/2021 01:44:15 - INFO - transformers.tokenization_utils -   loading file https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/vocab.txt from cache at /home/.cache/torch/transformers/ea1474aad40c1c8ed4e1cb7c11345ddda6df27a857fb29e1d4c901d9b900d32d.26f8bd5a32e49c2a8271a46950754a4a767726709b7741c68723bc1db840a87e
01/08/2021 01:44:15 - INFO - __main__ -   Training new model from scratch
01/08/2021 01:44:19 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-06, beta1=0.9, beta2=0.98, block_size=512, cache_dir=None, config_name='/home/DNABERT/src/transformers/dnabert-config/bert-config-6-mm', device=device(type='cuda', index=0), do_eval=True, do_train=True, eval_all_checkpoints=False, eval_data_file='/home/DNABERT/examples/sample_data/pre/GRCh38.dna.primary_assembly_cut6_test.txt', evaluate_during_training=True, fp16=True, fp16_opt_level='O1', gradient_accumulation_steps=25, learning_rate=0.0004, line_by_line=True, local_rank=-1, logging_steps=500, max_grad_norm=1.0, max_steps=200000, mlm=True, mlm_probability=0.025, model_name_or_path=None, model_type='dna', n_gpu=1, n_process=4, no_cuda=False, num_train_epochs=1.0, output_dir='output6-mm', overwrite_cache=False, overwrite_output_dir=True, per_gpu_eval_batch_size=6, per_gpu_train_batch_size=10, save_steps=500, save_total_limit=20, seed=42, server_ip='', server_port='', should_continue=False, tokenizer_name='dna6', train_data_file='/home/DNABERT/examples/sample_data/pre/GRCh38.dna.primary_assembly_cut6_train.txt', warmup_steps=10000, weight_decay=0.01)
01/08/2021 01:44:19 - INFO - __main__ -   Creating features from dataset file at /home/DNABERT/examples/sample_data/pre/GRCh38.dna.primary_assembly_cut6_train.txt
Traceback (most recent call last):
  File "run_pretrain.py", line 885, in <module>
    main()
  File "run_pretrain.py", line 830, in main
    train_dataset = load_and_cache_examples(args, tokenizer, evaluate=False)
  File "run_pretrain.py", line 200, in load_and_cache_examples
    return LineByLineTextDataset(tokenizer, args, file_path=file_path, block_size=args.block_size)
  File "run_pretrain.py", line 183, in __init__
    ids = result.get()
  File "/gpfs/project/conda_envs/dnabert/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/gpfs/project/conda_envs/dnabert/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/gpfs/project/conda_envs/dnabert/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/gpfs/project/conda_envs/dnabert/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by Zhihan1996** [comment]
This problem results from python's limitation in sharing data between multiple processing. Please create an environment with python 3.8 and it should be fine.

**Comment by gianfilippo** [comment]
Hi,

I reinstalled the dnabert as conda env, overriding the old one. I used Python 3.8, but the result is the same (see below)

2021-01-10 11:44:50.793443: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
01/10/2021 11:45:18 - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 4, distributed training: False, 16-bits training: False
01/10/2021 11:45:18 - INFO - transformers.configuration_utils -   loading configuration file /home/DNABERT/src/transformers/dnabert-config/bert-config-6/config.json
01/10/2021 11:45:18 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "do_sample": false,
  "eos_token_ids": 0,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_beams": 1,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "num_return_sequences": 1,
  "num_rnn_layer": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": 0,
  "pruned_heads": {},
  "repetition_penalty": 1.0,
  "rnn": "lstm",
  "rnn_dropout": 0.0,
  "rnn_hidden": 768,
  "split": 10,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 4101
}

01/10/2021 11:45:18 - INFO - transformers.tokenization_utils -   loading file https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/vocab.txt from cache at /home/.cache/torch/transformers/ea1474aad40c1c8ed4e1cb7c11345ddda6df27a857fb29e1d4c901d9b900d32d.26f8bd5a32e49c2a8271a46950754a4a767726709b7741c68723bc1db840a87e
01/10/2021 11:45:18 - INFO - __main__ -   Training new model from scratch
01/10/2021 11:45:38 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-06, beta1=0.9, beta2=0.98, block_size=512, cache_dir=None, config_name='/home/DNABERT/src/transformers/dnabert-config/bert-config-6', device=device(type='cuda', index=0), do_eval=True, do_train=True, eval_all_checkpoints=False, eval_data_file='sample_data/pre/6_3k_ORIG.txt', evaluate_during_training=True, fp16=False, fp16_opt_level='O1', gradient_accumulation_steps=25, learning_rate=0.0004, line_by_line=True, local_rank=-1, logging_steps=500, max_grad_norm=1.0, max_steps=200000, mlm=True, mlm_probability=0.025, model_name_or_path=None, model_type='dna', n_gpu=4, n_process=1, no_cuda=False, num_train_epochs=1.0, output_dir='output6', overwrite_cache=False, overwrite_output_dir=True, per_gpu_eval_batch_size=6, per_gpu_train_batch_size=10, save_steps=500, save_total_limit=20, seed=42, server_ip='', server_port='', should_continue=False, tokenizer_name='dna6', train_data_file='sample_data/pre/6_3k_ORIG.txt', warmup_steps=1000, weight_decay=0.01)
01/10/2021 11:45:38 - INFO - __main__ -   Loading features from cached file sample_data/pre/dna_cached_lm_512_6_3k_ORIG.txt
01/10/2021 11:45:38 - INFO - __main__ -   ***** Running training *****
01/10/2021 11:45:38 - INFO - __main__ -     Num examples = 3000
01/10/2021 11:45:38 - INFO - __main__ -     Num Epochs = 66667
01/10/2021 11:45:38 - INFO - __main__ -     Instantaneous batch size per GPU = 10
01/10/2021 11:45:38 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 1000
01/10/2021 11:45:38 - INFO - __main__ -     Gradient Accumulation steps = 25
01/10/2021 11:45:38 - INFO - __main__ -     Total optimization steps = 200000
Iteration:   0%|          | 0/75 [00:08<?, ?it/s]
Epoch:   0%|          | 0/66667 [00:08<?, ?it/s]]
Traceback (most recent call last):
  File "run_pretrain.py", line 887, in <module>
    main()
  File "run_pretrain.py", line 837, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "run_pretrain.py", line 433, in train
    outputs = model(inputs, masked_lm_labels=labels) if args.mlm else model(inputs, labels=labels)
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/DNABERT/src/transformers/modeling_bert.py", line 990, in forward
    outputs = self.bert(
  File "/gpfs/conda_envs/dnabert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfsDNABERT/src/transformers/modeling_bert.py", line 745, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
StopIteration

**Comment by Zhihan1996** [comment]
sorry for the late reply. Do you successfully install the ```apex``` package for fp16 training? Could you try to run the model without the ```--fp16``` tag?

**Comment by gianfilippo** [comment]
Hi, at this point I can only run it without the --fp16 tag. Not ideal, but it runs.
I am trying to reproduce your results. I tried to follow your processing, and i realized that I do not know how you process the "N" in the genome. Can you please explain ?
Also, can you please confirm that the special tokens are added within the script ?
Thanks

**Comment by Zhihan1996** [comment]
For --fp16, you need to install the Nvidia/apex package. For genome, we just throw away all the "N". I believe the special tokens are added.

**Comment by gianfilippo** [comment]
HI,
the problem seems to be with the installation of the Nvidia/apex package. I
do not have time now to debug this.
I am asking about the special tokens because then example, file does not
show them. So I assume they are added in the script.
Thanks for the details
